name: Unit Testing & Sonar

on:
  workflow_dispatch:
  pull_request:
    paths: ['packages/ethers/**', 'packages/vechain/**', 'packages/web3/**', '.github/workflows/**']
    branches:
      - main


jobs:
  run-tests-and-build-report:
    name: Test + build report
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
      packages: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 

      - name: Use Node v18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'
          registry-url: 'https://npm.pkg.github.com'
          always-auth: true
          scope: '@vechainfoundation'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}      

      - name: Install dependencies
        run: | 
          yarn install
          yarn build
          
      - name: Unit tests and coverage
        run:  yarn workspace @vechain/hardhat-vechain test-coverage

  upload-coverage-to-sonar:
    name: Upload coverage report to Sonar and quality gate check
    runs-on: ubuntu-latest
    needs: run-tests-and-build-report
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
